# Don't edit the `bin` list manually! It is updated by `rustlings dev update`
bin = [
  { name = "grid_beweging", path = "exercises/stories/grid_beweging.rs" },
  { name = "grid_beweging_sol", path = "solutions/stories/grid_beweging.rs" },
  { name = "vuurbal", path = "exercises/stories/vuurbal.rs" },
  { name = "vuurbal_sol", path = "solutions/stories/vuurbal.rs" },
  { name = "collatz", path = "exercises/stories/collatz.rs" },
  { name = "collatz_sol", path = "solutions/stories/collatz.rs" },
  { name = "frogger", path = "exercises/stories/frogger.rs" },
  { name = "frogger_sol", path = "solutions/stories/frogger.rs" },
]

[package]
name = "exercises"
edition = "2024"
# Don't publish the exercises on crates.io!
publish = false

[dependencies]
anyhow = "1.0.103"


[lints.clippy]
correctness = "deny"
suspicious = "deny"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "deny"
