# Don't edit the `bin` list manually! It is updated by `rustlings dev update`
bin = [
  { name = "1_hallo_rust", path = "exercises/artikel_1/1_hallo_rust.rs" },
  { name = "2_hallo_naam", path = "exercises/artikel_1/2_hallo_naam.rs" },
  { name = "3_eerste_game", path = "exercises/artikel_1/3_eerste_game.rs" },
  { name = "4_volgorde", path = "exercises/artikel_1/4_volgorde.rs" },
  { name = "5_meer_tekst", path = "exercises/artikel_1/5_meer_tekst.rs" },
  { name = "6_fout_1", path = "exercises/artikel_1/6_fout_1.rs" },
  { name = "6_fout_1_sol", path = "solutions/artikel_1/6_fout_1.rs" },
  { name = "7_fout_2", path = "exercises/artikel_1/7_fout_2.rs" },
  { name = "7_fout_2_sol", path = "solutions/artikel_1/7_fout_2.rs" },
  { name = "8_startscherm", path = "exercises/artikel_1/8_startscherm.rs" },
  { name = "9_begin_game", path = "exercises/artikel_1/9_begin_game.rs" },
  { name = "1_fout_1", path = "exercises/artikel_2/1_fout_1.rs" },
  { name = "1_fout_1_sol", path = "solutions/artikel_2/1_fout_1.rs" },
  { name = "2_fout_2", path = "exercises/artikel_2/2_fout_2.rs" },
  { name = "2_fout_2_sol", path = "solutions/artikel_2/2_fout_2.rs" },
  { name = "1_naam_variabele", path = "exercises/artikel_3/1_naam_variabele.rs" },
  { name = "2_levens_variabele", path = "exercises/artikel_3/2_levens_variabele.rs" },
  { name = "3_score", path = "exercises/artikel_3/3_score.rs" },
  { name = "4_schade", path = "exercises/artikel_3/4_schade.rs" },
  { name = "5_goud", path = "exercises/artikel_3/5_goud.rs" },
  { name = "6_punten", path = "exercises/artikel_3/6_punten.rs" },
  { name = "7_schade_2", path = "exercises/artikel_3/7_schade_2.rs" },
  { name = "8_totale_schade", path = "exercises/artikel_3/8_totale_schade.rs" },
  { name = "9_ervaring", path = "exercises/artikel_3/9_ervaring.rs" },
  { name = "10_maximaal_huidig", path = "exercises/artikel_3/10_maximaal_huidig.rs" },
  { name = "11_winkel", path = "exercises/artikel_3/11_winkel.rs" },
  { name = "12_statistieken", path = "exercises/artikel_3/12_statistieken.rs" },
  { name = "13_fout_1", path = "exercises/artikel_3/13_fout_1.rs" },
  { name = "14_fout_2", path = "exercises/artikel_3/14_fout_2.rs" },
  { name = "15_muteerbaar", path = "exercises/artikel_3/15_muteerbaar.rs" },
  { name = "1_functie", path = "exercises/artikel_4/1_functie.rs" },
  { name = "1_functie_sol", path = "solutions/artikel_4/1_functie.rs" },
  { name = "2_aanroepen", path = "exercises/artikel_4/2_aanroepen.rs" },
  { name = "2_aanroepen_sol", path = "solutions/artikel_4/2_aanroepen.rs" },
  { name = "3_parameters", path = "exercises/artikel_4/3_parameters.rs" },
  { name = "3_parameters_sol", path = "solutions/artikel_4/3_parameters.rs" },
  { name = "4_resultaat", path = "exercises/artikel_4/4_resultaat.rs" },
  { name = "4_resultaat_sol", path = "solutions/artikel_4/4_resultaat.rs" },
  { name = "1_regel", path = "exercises/artikel_5/1_regel.rs" },
  { name = "1_regel_sol", path = "solutions/artikel_5/1_regel.rs" },
  { name = "2_bericht", path = "exercises/artikel_5/2_bericht.rs" },
  { name = "2_bericht_sol", path = "solutions/artikel_5/2_bericht.rs" },
  { name = "3_meer_regels", path = "exercises/artikel_5/3_meer_regels.rs" },
  { name = "3_meer_regels_sol", path = "solutions/artikel_5/3_meer_regels.rs" },
  { name = "1_levens", path = "exercises/artikel_6/1_levens.rs" },
  { name = "1_levens_sol", path = "solutions/artikel_6/1_levens.rs" },
  { name = "2_even", path = "exercises/artikel_6/2_even.rs" },
  { name = "2_even_sol", path = "solutions/artikel_6/2_even.rs" },
  { name = "3_rang", path = "exercises/artikel_6/3_rang.rs" },
  { name = "3_rang_sol", path = "solutions/artikel_6/3_rang.rs" },
  { name = "4_game_over", path = "exercises/artikel_6/4_game_over.rs" },
  { name = "4_game_over_sol", path = "solutions/artikel_6/4_game_over.rs" },
  { name = "1_lus", path = "exercises/artikel_7/1_lus.rs" },
  { name = "1_lus_sol", path = "solutions/artikel_7/1_lus.rs" },
  { name = "2_while_lus", path = "exercises/artikel_7/2_while_lus.rs" },
  { name = "2_while_lus_sol", path = "solutions/artikel_7/2_while_lus.rs" },
  { name = "3_for_lus", path = "exercises/artikel_7/3_for_lus.rs" },
  { name = "3_for_lus_sol", path = "solutions/artikel_7/3_for_lus.rs" },
  { name = "4_aoe_schade", path = "exercises/artikel_7/4_aoe_schade.rs" },
  { name = "4_aoe_schade_sol", path = "solutions/artikel_7/4_aoe_schade.rs" },
  { name = "1_string", path = "exercises/artikel_8/1_string.rs" },
  { name = "1_string_sol", path = "solutions/artikel_8/1_string.rs" },
  { name = "2_move", path = "exercises/artikel_8/2_move.rs" },
  { name = "2_move_sol", path = "solutions/artikel_8/2_move.rs" },
  { name = "3_clone", path = "exercises/artikel_8/3_clone.rs" },
  { name = "3_clone_sol", path = "solutions/artikel_8/3_clone.rs" },
  { name = "4_functie", path = "exercises/artikel_8/4_functie.rs" },
  { name = "4_functie_sol", path = "solutions/artikel_8/4_functie.rs" },
  { name = "5_naam", path = "exercises/artikel_8/5_naam.rs" },
  { name = "5_naam_sol", path = "solutions/artikel_8/5_naam.rs" },
  { name = "1_lenen", path = "exercises/artikel_9/1_lenen.rs" },
  { name = "1_lenen_sol", path = "solutions/artikel_9/1_lenen.rs" },
  { name = "2_tekst", path = "exercises/artikel_9/2_tekst.rs" },
  { name = "2_tekst_sol", path = "solutions/artikel_9/2_tekst.rs" },
  { name = "3_schade", path = "exercises/artikel_9/3_schade.rs" },
  { name = "3_schade_sol", path = "solutions/artikel_9/3_schade.rs" },
  { name = "4_aanpassen", path = "exercises/artikel_9/4_aanpassen.rs" },
  { name = "4_aanpassen_sol", path = "solutions/artikel_9/4_aanpassen.rs" },
  { name = "5_twee_keer", path = "exercises/artikel_9/5_twee_keer.rs" },
  { name = "5_twee_keer_sol", path = "solutions/artikel_9/5_twee_keer.rs" },
  { name = "1_struct", path = "exercises/artikel_10/1_struct.rs" },
  { name = "1_struct_sol", path = "solutions/artikel_10/1_struct.rs" },
  { name = "2_velden", path = "exercises/artikel_10/2_velden.rs" },
  { name = "2_velden_sol", path = "solutions/artikel_10/2_velden.rs" },
  { name = "3_veranderen", path = "exercises/artikel_10/3_veranderen.rs" },
  { name = "3_veranderen_sol", path = "solutions/artikel_10/3_veranderen.rs" },
  { name = "4_lenen", path = "exercises/artikel_10/4_lenen.rs" },
  { name = "4_lenen_sol", path = "solutions/artikel_10/4_lenen.rs" },
  { name = "5_vijand", path = "exercises/artikel_10/5_vijand.rs" },
  { name = "5_vijand_sol", path = "solutions/artikel_10/5_vijand.rs" },
  { name = "1_method", path = "exercises/artikel_11/1_method.rs" },
  { name = "1_method_sol", path = "solutions/artikel_11/1_method.rs" },
  { name = "2_naam", path = "exercises/artikel_11/2_naam.rs" },
  { name = "2_naam_sol", path = "solutions/artikel_11/2_naam.rs" },
  { name = "3_method_schade", path = "exercises/artikel_11/3_method_schade.rs" },
  { name = "3_method_schade_sol", path = "solutions/artikel_11/3_method_schade.rs" },
  { name = "4_levend", path = "exercises/artikel_11/4_levend.rs" },
  { name = "4_levend_sol", path = "solutions/artikel_11/4_levend.rs" },
  { name = "5_genezen", path = "exercises/artikel_11/5_genezen.rs" },
  { name = "5_genezen_sol", path = "solutions/artikel_11/5_genezen.rs" },
  { name = "1_wapen", path = "exercises/artikel_12/1_wapen.rs" },
  { name = "1_wapen_sol", path = "solutions/artikel_12/1_wapen.rs" },
  { name = "2_actie", path = "exercises/artikel_12/2_actie.rs" },
  { name = "2_actie_sol", path = "solutions/artikel_12/2_actie.rs" },
  { name = "3_match", path = "exercises/artikel_12/3_match.rs" },
  { name = "3_match_sol", path = "solutions/artikel_12/3_match.rs" },
  { name = "4_enum_schade", path = "exercises/artikel_12/4_enum_schade.rs" },
  { name = "4_enum_schade_sol", path = "solutions/artikel_12/4_enum_schade.rs" },
  { name = "5_status", path = "exercises/artikel_12/5_status.rs" },
  { name = "5_status_sol", path = "solutions/artikel_12/5_status.rs" },
  { name = "1_trait", path = "exercises/artikel_13/1_trait.rs" },
  { name = "1_trait_sol", path = "solutions/artikel_13/1_trait.rs" },
  { name = "2_speler", path = "exercises/artikel_13/2_speler.rs" },
  { name = "2_speler_sol", path = "solutions/artikel_13/2_speler.rs" },
  { name = "3_vijand", path = "exercises/artikel_13/3_vijand.rs" },
  { name = "3_vijand_sol", path = "solutions/artikel_13/3_vijand.rs" },
  { name = "4_trait_levend", path = "exercises/artikel_13/4_trait_levend.rs" },
  { name = "4_trait_levend_sol", path = "solutions/artikel_13/4_trait_levend.rs" },
  { name = "1_debug", path = "exercises/artikel_14/1_debug.rs" },
  { name = "1_debug_sol", path = "solutions/artikel_14/1_debug.rs" },
  { name = "2_clone", path = "exercises/artikel_14/2_clone.rs" },
  { name = "2_clone_sol", path = "solutions/artikel_14/2_clone.rs" },
  { name = "3_gelijk", path = "exercises/artikel_14/3_gelijk.rs" },
  { name = "3_gelijk_sol", path = "solutions/artikel_14/3_gelijk.rs" },
  { name = "4_default", path = "exercises/artikel_14/4_default.rs" },
  { name = "4_default_sol", path = "solutions/artikel_14/4_default.rs" },
  { name = "1_closure", path = "exercises/artikel_16/1_closure.rs" },
  { name = "1_closure_sol", path = "solutions/artikel_16/1_closure.rs" },
  { name = "2_parameters", path = "exercises/artikel_16/2_parameters.rs" },
  { name = "2_parameters_sol", path = "solutions/artikel_16/2_parameters.rs" },
  { name = "3_bonus", path = "exercises/artikel_16/3_bonus.rs" },
  { name = "3_bonus_sol", path = "solutions/artikel_16/3_bonus.rs" },
  { name = "4_aanval", path = "exercises/artikel_16/4_aanval.rs" },
  { name = "4_aanval_sol", path = "solutions/artikel_16/4_aanval.rs" },
  { name = "1_test", path = "exercises/artikel_17/1_test.rs" },
  { name = "1_test_sol", path = "solutions/artikel_17/1_test.rs" },
  { name = "2_schade_test", path = "exercises/artikel_17/2_schade_test.rs" },
  { name = "2_schade_test_sol", path = "solutions/artikel_17/2_schade_test.rs" },
  { name = "3_assert", path = "exercises/artikel_17/3_assert.rs" },
  { name = "3_assert_sol", path = "solutions/artikel_17/3_assert.rs" },
  { name = "4_meerdere_tests", path = "exercises/artikel_17/4_meerdere_tests.rs" },
  { name = "4_meerdere_tests_sol", path = "solutions/artikel_17/4_meerdere_tests.rs" },
  { name = "1_opbouwen", path = "exercises/artikel_18/1_opbouwen.rs" },
  { name = "1_opbouwen_sol", path = "solutions/artikel_18/1_opbouwen.rs" },
  { name = "2_lenen", path = "exercises/artikel_18/2_lenen.rs" },
  { name = "2_lenen_sol", path = "solutions/artikel_18/2_lenen.rs" },
  { name = "3_eerste_woord", path = "exercises/artikel_18/3_eerste_woord.rs" },
  { name = "3_eerste_woord_sol", path = "solutions/artikel_18/3_eerste_woord.rs" },
  { name = "4_contains", path = "exercises/artikel_18/4_contains.rs" },
  { name = "4_contains_sol", path = "solutions/artikel_18/4_contains.rs" },
  { name = "1_module", path = "exercises/artikel_19/1_module.rs" },
  { name = "1_module_sol", path = "solutions/artikel_19/1_module.rs" },
  { name = "2_pub", path = "exercises/artikel_19/2_pub.rs" },
  { name = "2_pub_sol", path = "solutions/artikel_19/2_pub.rs" },
  { name = "3_struct", path = "exercises/artikel_19/3_struct.rs" },
  { name = "3_struct_sol", path = "solutions/artikel_19/3_struct.rs" },
  { name = "4_game", path = "exercises/artikel_19/4_game.rs" },
  { name = "4_game_sol", path = "solutions/artikel_19/4_game.rs" },
  { name = "1_some", path = "exercises/artikel_20/1_some.rs" },
  { name = "1_some_sol", path = "solutions/artikel_20/1_some.rs" },
  { name = "2_none", path = "exercises/artikel_20/2_none.rs" },
  { name = "2_none_sol", path = "solutions/artikel_20/2_none.rs" },
  { name = "3_wapen", path = "exercises/artikel_20/3_wapen.rs" },
  { name = "3_wapen_sol", path = "solutions/artikel_20/3_wapen.rs" },
  { name = "4_zoeken", path = "exercises/artikel_20/4_zoeken.rs" },
  { name = "4_zoeken_sol", path = "solutions/artikel_20/4_zoeken.rs" },
  { name = "1_ok", path = "exercises/artikel_21/1_ok.rs" },
  { name = "1_ok_sol", path = "solutions/artikel_21/1_ok.rs" },
  { name = "2_err", path = "exercises/artikel_21/2_err.rs" },
  { name = "2_err_sol", path = "solutions/artikel_21/2_err.rs" },
  { name = "3_result_match", path = "exercises/artikel_21/3_result_match.rs" },
  { name = "3_result_match_sol", path = "solutions/artikel_21/3_result_match.rs" },
  { name = "4_delen", path = "exercises/artikel_21/4_delen.rs" },
  { name = "4_delen_sol", path = "solutions/artikel_21/4_delen.rs" },
  { name = "1_iter", path = "exercises/artikel_22/1_iter.rs" },
  { name = "1_iter_sol", path = "solutions/artikel_22/1_iter.rs" },
  { name = "2_map", path = "exercises/artikel_22/2_map.rs" },
  { name = "2_map_sol", path = "solutions/artikel_22/2_map.rs" },
  { name = "3_filter", path = "exercises/artikel_22/3_filter.rs" },
  { name = "3_filter_sol", path = "solutions/artikel_22/3_filter.rs" },
  { name = "4_collect", path = "exercises/artikel_22/4_collect.rs" },
  { name = "4_collect_sol", path = "solutions/artikel_22/4_collect.rs" },
  { name = "1_generiek", path = "exercises/artikel_23/1_generiek.rs" },
  { name = "1_generiek_sol", path = "solutions/artikel_23/1_generiek.rs" },
  { name = "2_kist", path = "exercises/artikel_23/2_kist.rs" },
  { name = "2_kist_sol", path = "solutions/artikel_23/2_kist.rs" },
  { name = "3_display", path = "exercises/artikel_23/3_display.rs" },
  { name = "3_display_sol", path = "solutions/artikel_23/3_display.rs" },
  { name = "4_eerste", path = "exercises/artikel_23/4_eerste.rs" },
  { name = "4_eerste_sol", path = "solutions/artikel_23/4_eerste.rs" },
  { name = "1_inventory", path = "exercises/artikel_24/1_inventory.rs" },
  { name = "1_inventory_sol", path = "solutions/artikel_24/1_inventory.rs" },
  { name = "2_score", path = "exercises/artikel_24/2_score.rs" },
  { name = "2_score_sol", path = "solutions/artikel_24/2_score.rs" },
  { name = "3_entry", path = "exercises/artikel_24/3_entry.rs" },
  { name = "3_entry_sol", path = "solutions/artikel_24/3_entry.rs" },
  { name = "4_tellen", path = "exercises/artikel_24/4_tellen.rs" },
  { name = "4_tellen_sol", path = "solutions/artikel_24/4_tellen.rs" },
  { name = "1_bestand", path = "exercises/artikel_25/1_bestand.rs" },
  { name = "1_bestand_sol", path = "solutions/artikel_25/1_bestand.rs" },
  { name = "1_structuur", path = "exercises/artikel_26/1_structuur.rs" },
  { name = "1_structuur_sol", path = "solutions/artikel_26/1_structuur.rs" },
  { name = "1_ontwerp", path = "exercises/artikel_27/1_ontwerp.rs" },
  { name = "1_ontwerp_sol", path = "solutions/artikel_27/1_ontwerp.rs" },
  { name = "1_rpg", path = "exercises/artikel_28/1_rpg.rs" },
  { name = "1_rpg_sol", path = "solutions/artikel_28/1_rpg.rs" },
  { name = "1_uitrusting", path = "exercises/artikel_29/1_uitrusting.rs" },
  { name = "1_uitrusting_sol", path = "solutions/artikel_29/1_uitrusting.rs" },
  { name = "1_wereld", path = "exercises/artikel_30/1_wereld.rs" },
  { name = "1_wereld_sol", path = "solutions/artikel_30/1_wereld.rs" },
  { name = "1_spel_lus", path = "exercises/artikel_31/1_spel_lus.rs" },
  { name = "1_spel_lus_sol", path = "solutions/artikel_31/1_spel_lus.rs" },
  { name = "1_gevecht", path = "exercises/artikel_32/1_gevecht.rs" },
  { name = "1_gevecht_sol", path = "solutions/artikel_32/1_gevecht.rs" },
  { name = "1_beloning", path = "exercises/artikel_33/1_beloning.rs" },
  { name = "1_beloning_sol", path = "solutions/artikel_33/1_beloning.rs" },
  { name = "1_npc", path = "exercises/artikel_34/1_npc.rs" },
  { name = "1_npc_sol", path = "solutions/artikel_34/1_npc.rs" },
  { name = "1_consolideren", path = "exercises/artikel_35/1_consolideren.rs" },
  { name = "1_consolideren_sol", path = "solutions/artikel_35/1_consolideren.rs" },
  { name = "1_refactor", path = "exercises/artikel_36/1_refactor.rs" },
  { name = "1_refactor_sol", path = "solutions/artikel_36/1_refactor.rs" },
  { name = "1_eindproject", path = "exercises/artikel_37/1_eindproject.rs" },
  { name = "1_eindproject_sol", path = "solutions/artikel_37/1_eindproject.rs" },
  { name = "1_array", path = "exercises/artikel_15/1_array.rs" },
  { name = "1_array_sol", path = "solutions/artikel_15/1_array.rs" },
  { name = "2_vec", path = "exercises/artikel_15/2_vec.rs" },
  { name = "2_vec_sol", path = "solutions/artikel_15/2_vec.rs" },
  { name = "3_push", path = "exercises/artikel_15/3_push.rs" },
  { name = "3_push_sol", path = "solutions/artikel_15/3_push.rs" },
  { name = "4_for", path = "exercises/artikel_15/4_for.rs" },
  { name = "4_for_sol", path = "solutions/artikel_15/4_for.rs" },
  { name = "5_aoe", path = "exercises/artikel_15/5_aoe.rs" },
  { name = "5_aoe_sol", path = "solutions/artikel_15/5_aoe.rs" },
]

[package]
name = "exercises"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.104"
itertools = "0.15.0"
rand = "0.10.2"
static_assertions = "1.1.0"


[lints.clippy]
correctness = "deny"
suspicious = "deny"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "warn"
