# Don't edit the `bin` list manually! It is updated by `rustlings dev update`
bin = [
  { name = "grid_beweging", path = "exercises/grid_beweging.rs" },
  { name = "grid_beweging_sol", path = "solutions/grid_beweging.rs" },
]

[package]
name = "exercises"
edition = "2024"
# Don't publish the exercises on crates.io!
publish = false

[dependencies]


[lints.clippy]
correctness = "deny"
suspicious = "deny"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "deny"
