format_version = 1
welcome_message = """Welkom bij de KeiTV Rustlings oefeningen"""
final_message = """Je hebt alle oefeningen gedaan. Hopelijk was het leerzaam."""

[[exercises]]
name = "variables1"
dir = "book_ch3"
test = false
strict_clippy = true
hint = """Volg de instructies in het commentaar van de main functie"""

[[exercises]]
name = "variables2"
dir = "book_ch3"
test = false
strict_clippy = true
hint = """Volg de instructies in het commentaar van de main functie"""

[[exercises]]
name = "variables3"
dir = "book_ch3"
test = false
strict_clippy = true
hint = """Volg de instructies in het commentaar van de main functie"""

[[exercises]]
name = "variables4"
dir = "book_ch3"
test = false
strict_clippy = true
hint = """Volg de instructies in het commentaar van de main functie"""

[[exercises]]
name = "variables5"
dir = "book_ch3"
test = false
strict_clippy = true
hint = """Volg de instructies in het commentaar van de main functie"""

[[exercises]]
name = "data_types1"
dir = "book_ch3"
test = false
strict_clippy = true
hint = """Volg de instructies in het commentaar van de main functie"""

[[exercises]]
name = "data_types2"
dir = "book_ch3"
test = true
strict_clippy = true
hint = """Volg de instructies in het commentaar van de main functie"""

[[exercises]]
name = "grid_beweging"
dir = "stories"
test = true
strict_clippy = true
hint = """Schrijf eerst de verschillende bewegingsrichtingen uit. Probeer daarna te vereenvoudigen."""

[[exercises]]
name = "vuurbal"
dir = "stories"
test = true
strict_clippy = true
hint = """Je hebt geen ingewikkelde formules nodig.
Voorbeeld: Als je met de auto 100 kilometer per uur rijd, dan heb je na een uur 100 kilometer afgelegd.
Na een half uur (30 minuten) heb je hiervan de helft afgelegd, dus 50 kilometer.
Na 1 minuut heb je hiervan weer een dertigste afgelegd, dus 50/30 = 5/3 kilometer.
In zijn algemeenheid leg je na een tijd T in uren dus 100 * T kilometer af.
"""

[[exercises]]
name = "collatz"
dir = "stories"
test = true
strict_clippy = true
hint = """Vind jij het tegenvoorbeeld voor 120 miljoen japanse yen?"""

[[exercises]]
name = "frogger"
dir = "stories"
test = true
strict_clippy = true
hint = """Lees https://open.kattis.com/problems/1dfroggereasy en de code goed voordat je begint"""
